export const DELETE_ACCOUNT_ACCORDION_SECTIONS = [
  {
    id: "how-to",
    icon: "delete_forever",
    iconColor: "text-red-500",
    title: "How to Delete Your Account",
    subtitle: "Step-by-step process",
    content: [
      { step: "1", text: "Click the 'Permanently Delete Account' button above." },
      { step: "2", text: "Type DELETE in the confirmation field." },
      { step: "3", text: "Confirm your decision — this cannot be undone." },
      { step: "4", text: "Your product data is erased immediately, and only a minimal de-identified payment audit may remain." },
    ],
  },
  {
    id: "data-deleted",
    icon: "folder_off",
    iconColor: "text-hushh-blue",
    title: "Data That Will Be Permanently Deleted",
    subtitle: "Profile, history & preferences",
    content: [
      { step: "•", text: "Account credentials & profile information" },
      { step: "•", text: "Investor profile & preferences" },
      { step: "•", text: "Onboarding data & responses" },
      { step: "•", text: "Plaid-linked financial connection data" },
      { step: "•", text: "KYC verification data" },
      { step: "•", text: "Signed NDA records & uploaded PDFs" },
      { step: "•", text: "Chat history with AI assistant" },
      { step: "•", text: "Uploaded documents & files" },
      { step: "•", text: "Privacy settings & data vault" },
    ],
  },
  {
    id: "retention",
    icon: "history_toggle_off",
    iconColor: "text-ios-yellow",
    title: "Data Retention Policy",
    subtitle: "What we keep for compliance",
    content: [
      { step: "→", text: "Profile, onboarding, Plaid, NDA, KYC, chat, and file data are deleted immediately." },
      { step: "→", text: "Only a minimal de-identified payment audit is retained for compliance." },
      { step: "→", text: "We do not keep your onboarding, profile, or financial aggregation history after deletion." },
      { step: "→", text: "If you sign in again later, you will start with a brand-new empty account." },
    ],
  },
  {
    id: "notice",
    icon: "warning",
    iconColor: "text-ios-red",
    title: "Important Notice",
    subtitle: "Read before proceeding",
    content: [
      { step: "!", text: "This action is permanent and cannot be undone." },
      { step: "!", text: "You will lose access to all Hushh services immediately." },
      { step: "!", text: "Resolve any active investments or pending transactions before deleting." },
      { step: "!", text: "Signing in again later does not restore the deleted account or its data." },
      { step: "!", text: "Contact support@hushh.ai if you need help before deleting." },
    ],
  },
] as const;
