import { InvestorProfile, FIELD_LABELS, VALUE_LABELS } from '../../types/investorProfile';
import { NWSResult } from '../../services/networkScore/calculateNWS';
export type { InvestorProfile, NWSResult };
export { FIELD_LABELS, VALUE_LABELS };
interface FormState {
    name: string;
    email: string;
    age: number | "";
    phoneCountryCode: string;
    phoneNumber: string;
    organisation: string;
    accountType: string;
    selectedFund: string;
    referralSource: string;
    citizenshipCountry: string;
    residenceCountry: string;
    accountStructure: string;
    legalFirstName: string;
    legalLastName: string;
    addressLine1: string;
    city: string;
    state: string;
    zipCode: string;
    dateOfBirth: string;
    initialInvestmentAmount: number | "";
}
declare const defaultFormState: FormState;
export type { FormState };
export { defaultFormState };
export declare const useHushhUserProfileLogic: () => {
    form: FormState;
    setForm: import("react").Dispatch<import("react").SetStateAction<FormState>>;
    userId: string;
    investorProfile: InvestorProfile;
    setInvestorProfile: import("react").Dispatch<import("react").SetStateAction<InvestorProfile>>;
    profileSlug: string;
    loading: boolean;
    loadingSeconds: number;
    isProcessing: boolean;
    investorStatus: "error" | "done" | "running" | "idle";
    setLoading: import("react").Dispatch<import("react").SetStateAction<boolean>>;
    hasOnboardingData: boolean;
    isApplePassLoading: boolean;
    isGooglePassLoading: boolean;
    isWalletPreviewOpen: boolean;
    googleWalletSupported: boolean;
    googleWalletSupportMessage: string;
    appleWalletSupported: boolean;
    appleWalletSupportMessage: string;
    editingField: string;
    setEditingField: import("react").Dispatch<import("react").SetStateAction<string>>;
    nwsResult: NWSResult;
    nwsLoading: boolean;
    isFooterVisible: boolean;
    hasCopied: boolean;
    onCopy: (valueToCopy?: any) => void;
    profileUrl: string;
    navigate: import("react-router").NavigateFunction;
    toast: {
        (options?: import("@chakra-ui/react").UseToastOptions): import("@chakra-ui/react").ToastId;
        update(id: import("@chakra-ui/react").ToastId, options: Omit<import("@chakra-ui/react").UseToastOptions, "id">): void;
        promise<Result extends unknown, Err extends Error = Error>(promise: Promise<Result>, options: {
            success: import("node_modules/@chakra-ui/react/dist/types/toast/toast").MaybeFunction<import("node_modules/@chakra-ui/react/dist/types/toast/toast").UseToastPromiseOption, [Result]>;
            error: import("node_modules/@chakra-ui/react/dist/types/toast/toast").MaybeFunction<import("node_modules/@chakra-ui/react/dist/types/toast/toast").UseToastPromiseOption, [Err]>;
            loading: import("node_modules/@chakra-ui/react/dist/types/toast/toast").UseToastPromiseOption;
        }): void;
        closeAll: (options?: import("node_modules/@chakra-ui/react/dist/types/toast/toast.types").CloseAllToastsOptions | undefined) => void;
        close: (id: import("@chakra-ui/react").ToastId) => void;
        isActive: (id: import("@chakra-ui/react").ToastId) => boolean;
    };
    FIELD_OPTIONS: Record<string, {
        value: string;
        label: string;
    }[]>;
    MULTI_SELECT_FIELDS: string[];
    COUNTRIES: string[];
    defaultFormState: FormState;
    isDirty: boolean;
    isSaving: boolean;
    handleSaveChanges: () => Promise<void>;
    handleUpdateAIField: (fieldName: string, newValue: string | string[]) => void;
    handleMultiSelectToggle: (fieldName: string, optionValue: string) => void;
    handleChange: (key: keyof FormState, value: string) => void;
    handleSubmit: (e: React.FormEvent) => void;
    handleBack: () => void;
    handleSave: () => void;
    handleAppleWalletPass: () => Promise<void>;
    handleGoogleWalletPass: () => Promise<void>;
    openWalletPreview: () => void;
    closeWalletPreview: () => void;
    walletPreview: import("../../services/walletPass").WalletPreviewModel;
    handleShareWhatsApp: () => void;
    handleShareX: () => void;
    handleShareEmail: () => void;
    handleShareLinkedIn: () => void;
    handleOpenProfile: () => void;
    inputClassName: string;
    selectClassName: string;
    labelClassName: string;
    cardClassName: string;
    aiFieldCardTones: string[];
    getConfidenceLabel: (confidence: number) => "Low" | "High" | "Medium";
    getConfidenceBadgeClass: (confidence: number) => "border-emerald-200 bg-emerald-50 text-emerald-700" | "border-amber-200 bg-amber-50 text-amber-700" | "border-slate-200 bg-white/80 text-slate-600";
};
