export declare const DISPLAY_STEP: number;
export declare const TOTAL_STEPS: number;
export declare const PROGRESS_PCT: number;
export declare const MONTH_NAMES: string[];
export declare const MINIMUM_ONBOARDING_AGE = 18;
export declare const MINIMUM_DOB_YEAR = 1930;
export declare const buildDobYearOptions: (today?: Date, minimumYear?: number, minimumAge?: number) => string[];
export declare const resolveDobEligibility: (dobMonth: string, dobDay: string, dobYear: string, today?: Date) => {
    isComplete: boolean;
    isValidDate: boolean;
    isAdult: boolean;
    ageError: string | null;
};
export declare function useStep9Logic(): {
    ssn: string;
    dob: string;
    dobMonth: string;
    setDobMonth: import("react").Dispatch<import("react").SetStateAction<string>>;
    dobDay: string;
    setDobDay: import("react").Dispatch<import("react").SetStateAction<string>>;
    dobYear: string;
    setDobYear: import("react").Dispatch<import("react").SetStateAction<string>>;
    loading: boolean;
    error: string;
    showInfo: boolean;
    isFormValid: boolean;
    isFooterVisible: boolean;
    dateInputRef: import("react").MutableRefObject<HTMLInputElement>;
    yearOptions: string[];
    dayOptions: string[];
    daysInMonth: number;
    isUnder18: boolean;
    ageError: string;
    handleSSNChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    handleDobChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    handleNativeDateChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    openDatePicker: () => void;
    handleContinue: () => Promise<void>;
    handleSkip: () => Promise<void>;
    handleBack: () => void;
    handleShowInfoToggle: (open: boolean) => void;
};
